language: node_js

node_js:  
  - "node"

cache:
  apt: true
  directories:
    - node_modules

install:
  - echo 'KEY' >> $HOME/.ssh/known_hosts

addons:
  ssh_known_hosts: 47.98.99.250

script:  
  - npm install

after_script:  
  - npm run build