language: node_js

node_js:
  - node
cache:
  apt: true
  directories:
  - node_modules

addons:
  ssh_known_hosts:
  - 47.98.99.250

script:
- npm install

before_install:
  - openssl aes-256-cbc -K $encrypted_a3811aa9d454_key -iv $encrypted_a3811aa9d454_iv
  -in id_rsa.enc -out ~\.ssh/id_rsa -
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 47.98.99.250\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_script:
  - npm run build
