language: node_js
node_js:
- node
cache:
  apt: true
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 47.98.99.250
install:
  - echo 'sh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDImDBTa6KpZXhUOvN9Syukx4X0WwL7bmFpbUCBmXS9XMotUzLW6QmKBUnTDO7njDYjIfSJ4gz829kI1/FbJms4hBArXjXnKGOrZuPXWoSnCFBqLcrW9rSndJFHlQMZcQhbLMHj9fEa+w2RrSfty7CjQDBaR2Eei62r/oiZ3lnjdkI23/0vJItLegrcmYwAT1mdxo8+2S5YmV+x3f/dFINpuJ9K8gtpNKL/LEF7d6tYlceryfS539RAOSV/fO1Oq9hQyzkfj1k7rD+fUFDWuNsMQ9EFVNRgK3MGujWMw3m5ts68gEOxYcdpgZu0nXt33Kmp3BofT4GdqBMu5koS4LkZ huasheng@huanleguang.com' >> $HOME/.ssh/known_hosts
script:
  - npm install
after_script:
  - npm run build
