language: node_js
node_js:
- node
cache:
  apt: true
  directories:
  - node_modules
env:
  - SERVER_IP_ADDRESS=47.98.99.250
addons:
  ssh_known_hosts:
  - 47.98.99.250
script:
- npm install
after_script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_a3811aa9d454_key -iv $encrypted_a3811aa9d454_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@47.98.99.250 pwd